// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMNzvSBYTJKqD6LI3Sx6D0RadvYkvCI58',
    appId: '1:860082936357:web:8c677cf68e812684d03dcc',
    messagingSenderId: '860082936357',
    projectId: 'qrcode-bloc-6ff7f',
    authDomain: 'qrcode-bloc-6ff7f.firebaseapp.com',
    storageBucket: 'qrcode-bloc-6ff7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDogCtO0kGX8RzEHCkJC8X-AvMsBAJUl_o',
    appId: '1:860082936357:android:991cb149aee356ddd03dcc',
    messagingSenderId: '860082936357',
    projectId: 'qrcode-bloc-6ff7f',
    storageBucket: 'qrcode-bloc-6ff7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvf7YCk_OlYKscQnmVGjLJ7SnP6ziLVhE',
    appId: '1:860082936357:ios:dd11c02c1d0697b9d03dcc',
    messagingSenderId: '860082936357',
    projectId: 'qrcode-bloc-6ff7f',
    storageBucket: 'qrcode-bloc-6ff7f.appspot.com',
    iosBundleId: 'com.example.qrcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvf7YCk_OlYKscQnmVGjLJ7SnP6ziLVhE',
    appId: '1:860082936357:ios:c068e3748dec26d6d03dcc',
    messagingSenderId: '860082936357',
    projectId: 'qrcode-bloc-6ff7f',
    storageBucket: 'qrcode-bloc-6ff7f.appspot.com',
    iosBundleId: 'com.example.qrcode.RunnerTests',
  );
}
